# Generated by Django 5.1.2 on 2024-10-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='cat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sca.spycat'),
        ),
    ]
